"""
data-cycle-installer.py -- Self-contained installer for Data Cycle Domotic
===========================================================================
Generated by the Data Cycle install wizard. Config is embedded below.

Usage:
    python data-cycle-installer.py            (default: install to ./data-cycle-domotic)
    python data-cycle-installer.py /custom/path

What this does:
    1. Checks prerequisites (Python 3.11+, git, PostgreSQL reachable)
    2. Clones the repo
    3. Creates a Python venv and installs requirements
    4. Writes the .env file from the embedded config
    5. Creates PostgreSQL schemas (silver + gold)
    6. Runs the initial ETL (bronze -> silver -> gold)
    7. Prints next steps

Author: Group 14 - Data Cycle Project - HES-SO Valais 2026
"""

import os
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

# =============================================================================
# CONFIG (replaced by the web wizard at download time)
# =============================================================================

ENV_CONFIG = """\
# Bronze storage
SMB_PATH={{SMB_PATH}}
BRONZE_ROOT={{BRONZE_ROOT}}

# PostgreSQL (Silver/Gold)
DB_URL={{DB_URL}}

# MySQL source (school DB)
MYSQL_URL={{MYSQL_URL}}

# sFTP Weather
SFTP_HOST={{SFTP_HOST}}
SFTP_PORT={{SFTP_PORT}}
SFTP_USER={{SFTP_USER}}
SFTP_PASSWORD={{SFTP_PASSWORD}}
SFTP_PATH={{SFTP_PATH}}

WEATHER_MIN_YEAR={{WEATHER_MIN_YEAR}}

# Gold weather
WEATHER_SITES={{WEATHER_SITES}}

# Power BI connection (Gold schema)
PBI_SERVER={{PBI_SERVER}}
PBI_DATABASE={{PBI_DATABASE}}
PBI_USER={{PBI_USER}}
PBI_PASSWORD={{PBI_PASSWORD}}
"""

REPO_URL = "https://github.com/dehlya/data-cycle-domotic.git"
REPO_BRANCH = "deploy"
DEFAULT_INSTALL_DIR = "data-cycle-domotic"

# =============================================================================
# UI
# =============================================================================

RESET = "\033[0m"
BOLD  = "\033[1m"
DIM   = "\033[2m"
GREEN = "\033[32m"
RED   = "\033[31m"
YELLOW= "\033[33m"
BLUE  = "\033[36m"


def banner():
    print()
    print(f"{BOLD}{BLUE}╔══════════════════════════════════════════════════════════════╗{RESET}")
    print(f"{BOLD}{BLUE}║          Data Cycle Domotic -- Auto Installer                ║{RESET}")
    print(f"{BOLD}{BLUE}║          HES-SO Valais / Group 14                            ║{RESET}")
    print(f"{BOLD}{BLUE}╚══════════════════════════════════════════════════════════════╝{RESET}")
    print()


def step(num, total, message):
    print(f"\n{BOLD}[{num}/{total}] {message}{RESET}")


def ok(msg):
    print(f"  {GREEN}✓{RESET} {msg}")


def warn(msg):
    print(f"  {YELLOW}⚠{RESET} {msg}")


def fail(msg, hint=None):
    print(f"  {RED}✗ {msg}{RESET}")
    if hint:
        print(f"    {DIM}{hint}{RESET}")


def die(msg, hint=None):
    fail(msg, hint)
    print(f"\n{RED}{BOLD}Installation aborted.{RESET}\n")
    sys.exit(1)


# =============================================================================
# STEPS
# =============================================================================

def check_python():
    v = sys.version_info
    if (v.major, v.minor) < (3, 11):
        die(f"Python 3.11+ required, you have {v.major}.{v.minor}",
            "Install from https://www.python.org/downloads/")
    ok(f"Python {v.major}.{v.minor}.{v.micro}")


def check_cmd(cmd, hint=None):
    if shutil.which(cmd) is None:
        die(f"`{cmd}` not found in PATH", hint)
    ok(f"`{cmd}` available")


def parse_db_url(db_url: str):
    """Return (host, port, user, password, dbname) from a postgres URL."""
    import urllib.parse as up
    p = up.urlparse(db_url)
    return (
        p.hostname or "localhost",
        p.port or 5432,
        up.unquote(p.username or ""),
        up.unquote(p.password or ""),
        (p.path or "/").lstrip("/") or "postgres",
    )


def ensure_database_exists(venv: Path, db_url: str):
    """Check the target DB exists; if not, create it via the postgres maintenance DB."""
    host, port, user, password, dbname = parse_db_url(db_url)
    py = venv_python(venv)
    snippet = f"""
import sys
try:
    import psycopg2
except ImportError:
    sys.exit("psycopg2 not installed")

# Try to connect directly to target DB
try:
    c = psycopg2.connect(host="{host}", port={port}, user="{user}", password="{password}", dbname="{dbname}")
    c.close()
    print("EXISTS")
    sys.exit(0)
except psycopg2.OperationalError as e:
    if "does not exist" not in str(e).lower():
        sys.exit(f"FAIL:{{e}}")

# Create it from the postgres maintenance DB
try:
    c = psycopg2.connect(host="{host}", port={port}, user="{user}", password="{password}", dbname="postgres")
    c.autocommit = True
    cur = c.cursor()
    cur.execute('CREATE DATABASE "{dbname}"')
    cur.close(); c.close()
    print("CREATED")
except Exception as e:
    sys.exit(f"FAIL:{{e}}")
"""
    res = subprocess.run([str(py), "-c", snippet], capture_output=True, text=True)
    if res.returncode != 0:
        warn(f"DB check/create: {res.stdout.strip()}{res.stderr.strip()}")
        warn(f"You may need to create '{dbname}' manually, or check credentials.")
        return False
    out = res.stdout.strip()
    if out == "EXISTS":
        ok(f"Database '{dbname}' already exists")
    elif out == "CREATED":
        ok(f"Database '{dbname}' created")
    return True


def clone_repo(install_dir: Path):
    if install_dir.exists() and any(install_dir.iterdir()):
        warn(f"{install_dir} already exists and is not empty -- skipping clone")
        return
    install_dir.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["git", "clone", "--branch", REPO_BRANCH, "--depth", "1", REPO_URL, str(install_dir)],
        check=True
    )
    ok(f"Repo cloned to {install_dir}")


def write_env(install_dir: Path):
    env_path = install_dir / ".env"
    env_path.write_text(ENV_CONFIG, encoding="utf-8")
    ok(f".env written ({len(ENV_CONFIG)} chars)")


def create_venv(install_dir: Path) -> Path:
    venv = install_dir / ".venv"
    if venv.exists():
        warn(".venv already exists -- reusing")
    else:
        subprocess.run([sys.executable, "-m", "venv", str(venv)], check=True)
        ok("Virtual environment created")
    return venv


def venv_python(venv: Path) -> Path:
    if os.name == "nt":
        return venv / "Scripts" / "python.exe"
    return venv / "bin" / "python"


def install_deps(venv: Path, install_dir: Path):
    py = venv_python(venv)
    req = install_dir / "requirements.txt"
    if not req.exists():
        die(f"requirements.txt not found at {req}")
    subprocess.run([str(py), "-m", "pip", "install", "--upgrade", "pip"], check=True)
    subprocess.run([str(py), "-m", "pip", "install", "-r", str(req)], check=True)
    ok("Python dependencies installed")


def run_script(venv: Path, install_dir: Path, *args, label=None):
    py = venv_python(venv)
    env = os.environ.copy()
    env["PYTHONPATH"] = str(install_dir)
    try:
        subprocess.run([str(py), *args], cwd=str(install_dir), env=env, check=True)
        if label:
            ok(label)
    except subprocess.CalledProcessError as e:
        fail(f"{label or args} failed (exit {e.returncode})")
        raise


def create_schemas(venv: Path, install_dir: Path):
    run_script(venv, install_dir, "-m", "etl.bronze_to_silver.create_silver", label="Silver schema created")
    run_script(venv, install_dir, "-m", "etl.silver_to_gold.create_gold",     label="Gold schema created")


def run_initial_etl(venv: Path, install_dir: Path):
    run_script(venv, install_dir, "-m", "etl.silver_to_gold.populate_gold", label="Initial gold ETL complete")


# =============================================================================
# MAIN
# =============================================================================

def main():
    banner()

    # Where to install
    install_path = Path(sys.argv[1]).expanduser().resolve() if len(sys.argv) > 1 \
                   else Path.cwd() / DEFAULT_INSTALL_DIR

    print(f"Install target: {BOLD}{install_path}{RESET}")

    # ── 1. Prerequisites ─────────────────────────────────────────────────────
    step(1, 7, "Checking prerequisites")
    check_python()
    check_cmd("git", "Install Git from https://git-scm.com/downloads")

    # ── 2. Clone repo ────────────────────────────────────────────────────────
    step(2, 7, "Cloning repository")
    clone_repo(install_path)

    # ── 3. Write .env ────────────────────────────────────────────────────────
    step(3, 7, "Writing .env configuration")
    write_env(install_path)

    # ── 4. Create venv ───────────────────────────────────────────────────────
    step(4, 7, "Creating Python virtual environment")
    venv = create_venv(install_path)

    # ── 5. Install deps ──────────────────────────────────────────────────────
    step(5, 7, "Installing Python dependencies")
    install_deps(venv, install_path)

    # ── 6. Create DB + schemas ───────────────────────────────────────────────
    step(6, 7, "Ensuring PostgreSQL database and schemas")
    import re
    m = re.search(r"DB_URL=(.+)", ENV_CONFIG)
    if m:
        ensure_database_exists(venv, m.group(1).strip())
    try:
        create_schemas(venv, install_path)
    except Exception as e:
        warn(f"Schema creation had issues: {e}")
        warn("You may need to check DB_URL and rerun manually.")

    # ── 7. Initial ETL (optional — can take time) ────────────────────────────
    step(7, 7, "Running initial ETL (may take several minutes)")
    try:
        run_initial_etl(venv, install_path)
    except Exception as e:
        warn(f"Initial ETL had issues: {e}")
        warn("You can re-run manually: python -m etl.silver_to_gold.populate_gold")

    # ── Done ─────────────────────────────────────────────────────────────────
    print()
    print(f"{GREEN}{BOLD}╔══════════════════════════════════════════════════════════════╗{RESET}")
    print(f"{GREEN}{BOLD}║                     Installation complete!                   ║{RESET}")
    print(f"{GREEN}{BOLD}╚══════════════════════════════════════════════════════════════╝{RESET}")
    print()
    py_rel = venv_python(venv).relative_to(install_path) if venv_python(venv).is_relative_to(install_path) else venv_python(venv)
    print(f"{BOLD}Next steps:{RESET}")
    print(f"  {DIM}1.{RESET} Start the watcher (continuous pipeline):")
    print(f"     cd {install_path}")
    print(f"     {py_rel} ingestion/fast_flow/watcher.py")
    print()
    print(f"  {DIM}2.{RESET} Open the Power BI dashboard:")
    print(f"     {install_path / 'bi' / 'power_bi' / 'DataCycleDomotic.pbix'}")
    print()
    print(f"  {DIM}3.{RESET} In Power BI: Home -> Refresh  (loads latest gold data)")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n{YELLOW}Interrupted by user.{RESET}")
        sys.exit(130)
    except subprocess.CalledProcessError as e:
        print(f"\n{RED}{BOLD}A subprocess failed (exit {e.returncode}).{RESET}")
        print(f"{DIM}Command: {' '.join(str(x) for x in e.cmd)}{RESET}\n")
        sys.exit(1)
    except Exception as e:
        print(f"\n{RED}{BOLD}Unexpected error:{RESET} {e}")
        sys.exit(1)
