"""
data-cycle-installer.py -- Self-contained installer for Data Cycle Domotic
===========================================================================
Generated by the Data Cycle install wizard. Config is embedded below.

Usage:
    python data-cycle-installer.py            (default: install to ./data-cycle-domotic)
    python data-cycle-installer.py /custom/path

What this does:
    1. Checks prerequisites (Python 3.11+, git)
    2. Clones the repo
    3. Writes .env, creates venv, installs requirements
    4. Pre-flight: validates DB, MySQL, sFTP credentials
    5. Creates PostgreSQL database if missing + silver/gold schemas
    6. Runs the initial ETL (bronze -> silver -> gold)
    7. Verifies data landed (row counts)
    8. Offers to start the watcher

Author: Group 14 - Data Cycle Project - HES-SO Valais 2026
"""

import os
import shutil
import subprocess
import sys
import textwrap
from datetime import datetime
from pathlib import Path

# Force UTF-8 on Windows consoles so our box characters / ✓ / ✗ render
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

# =============================================================================
# CONFIG (replaced by the web wizard at download time)
# =============================================================================

ENV_CONFIG = """\
# Bronze storage
SMB_PATH={{SMB_PATH}}
BRONZE_ROOT={{BRONZE_ROOT}}

# PostgreSQL (Silver/Gold) — app user, not admin
DB_URL={{DB_URL}}

# MySQL source (school DB)
MYSQL_URL={{MYSQL_URL}}

# sFTP Weather
SFTP_HOST={{SFTP_HOST}}
SFTP_PORT={{SFTP_PORT}}
SFTP_USER={{SFTP_USER}}
SFTP_PASSWORD={{SFTP_PASSWORD}}
SFTP_PATH={{SFTP_PATH}}

WEATHER_MIN_YEAR={{WEATHER_MIN_YEAR}}

# Gold weather
WEATHER_SITES={{WEATHER_SITES}}

# Power BI connection (Gold schema) — app user
PBI_SERVER={{PBI_SERVER}}
PBI_DATABASE={{PBI_DATABASE}}
PBI_USER={{PBI_USER}}
PBI_PASSWORD={{PBI_PASSWORD}}
"""

# Admin credentials — used only during install, never written to .env
PG_HOST           = "{{PG_HOST}}"
PG_PORT           = "{{PG_PORT}}"
PG_ADMIN_USER     = "{{PG_ADMIN_USER}}"
PG_ADMIN_PASSWORD = "{{PG_ADMIN_PASSWORD}}"
PG_DATABASE       = "{{PG_DATABASE}}"
PG_APP_USER       = "{{PG_USER}}"
PG_APP_PASSWORD   = "{{PG_PASSWORD}}"

# SMB share (mount-time only, not written to .env)
SMB_SHARE    = "{{SMB_SHARE}}"
SMB_USER     = "{{SMB_USER}}"
SMB_PASSWORD = "{{SMB_PASSWORD}}"
SMB_DRIVE    = "{{SMB_DRIVE}}"

REPO_URL = "https://github.com/dehlya/data-cycle-domotic.git"
REPO_BRANCH = "release-final"  # switch to "main" once release-final is merged
DEFAULT_INSTALL_DIR = "data-cycle-domotic"

# =============================================================================
# UI
# =============================================================================

RESET = "\033[0m"
BOLD  = "\033[1m"
DIM   = "\033[2m"
GREEN = "\033[32m"
RED   = "\033[31m"
YELLOW= "\033[33m"
BLUE  = "\033[36m"

# Disable ANSI if output is being piped / redirected
if not sys.stdout.isatty():
    RESET = BOLD = DIM = GREEN = RED = YELLOW = BLUE = ""


class Summary:
    """Tracks what succeeded / failed for the final recap."""
    def __init__(self):
        self.ok = []
        self.skipped = []
        self.failed = []

    def add_ok(self, msg): self.ok.append(msg)
    def add_skipped(self, msg, reason): self.skipped.append((msg, reason))
    def add_failed(self, msg, reason): self.failed.append((msg, reason))

SUMMARY = Summary()
LOG_LINES = []


def log(msg):
    LOG_LINES.append(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}")


def banner():
    print()
    print(f"{BOLD}{BLUE}╔══════════════════════════════════════════════════════════════╗{RESET}")
    print(f"{BOLD}{BLUE}║          Data Cycle Domotic -- Auto Installer                ║{RESET}")
    print(f"{BOLD}{BLUE}║          HES-SO Valais / Group 14                            ║{RESET}")
    print(f"{BOLD}{BLUE}╚══════════════════════════════════════════════════════════════╝{RESET}")
    print()


def step(num, total, message):
    print(f"\n{BOLD}[{num}/{total}] {message}{RESET}")
    log(f"STEP {num}/{total}: {message}")


def ok(msg):
    print(f"  {GREEN}✓{RESET} {msg}")
    log(f"  OK: {msg}")


def warn(msg):
    print(f"  {YELLOW}⚠{RESET} {msg}")
    log(f"  WARN: {msg}")


def fail(msg, hint=None):
    print(f"  {RED}✗ {msg}{RESET}")
    log(f"  FAIL: {msg}")
    if hint:
        print(f"    {DIM}{hint}{RESET}")
        log(f"    hint: {hint}")


def die(msg, hint=None):
    fail(msg, hint)
    write_log()
    print(f"\n{RED}{BOLD}Installation aborted.{RESET}")
    print(f"{DIM}Log saved to install.log{RESET}\n")
    sys.exit(1)


def write_log():
    try:
        Path("install.log").write_text("\n".join(LOG_LINES) + "\n", encoding="utf-8")
    except Exception:
        pass


def ask_yes_no(prompt: str, default: bool = False) -> bool:
    suffix = " [Y/n]" if default else " [y/N]"
    try:
        ans = input(f"{BOLD}{prompt}{suffix}:{RESET} ").strip().lower()
    except EOFError:
        return default
    if not ans:
        return default
    return ans in ("y", "yes", "o", "oui")


# =============================================================================
# STEPS
# =============================================================================

def check_python():
    v = sys.version_info
    if (v.major, v.minor) < (3, 11):
        die(f"Python 3.11+ required, you have {v.major}.{v.minor}",
            "Install from https://www.python.org/downloads/")
    ok(f"Python {v.major}.{v.minor}.{v.micro}")


def check_cmd(cmd, hint=None):
    if shutil.which(cmd) is None:
        die(f"`{cmd}` not found in PATH", hint)
    ok(f"`{cmd}` available")


def parse_db_url(db_url: str):
    """Return (host, port, user, password, dbname) from a postgres URL."""
    import urllib.parse as up
    p = up.urlparse(db_url)
    return (
        p.hostname or "localhost",
        p.port or 5432,
        up.unquote(p.username or ""),
        up.unquote(p.password or ""),
        (p.path or "/").lstrip("/") or "postgres",
    )


def run_python_snippet(venv: Path, snippet: str) -> tuple[int, str, str]:
    """Run a one-line python snippet in the venv, return (code, stdout, stderr)."""
    py = venv_python(venv)
    res = subprocess.run([str(py), "-c", snippet], capture_output=True, text=True)
    return res.returncode, res.stdout.strip(), res.stderr.strip()


def validate_postgres_admin(venv: Path) -> bool:
    """Confirm we can reach Postgres as admin."""
    snippet = (
        "import sys\n"
        "try:\n"
        "    import psycopg2\n"
        "except ImportError:\n"
        "    sys.exit('NO_DRIVER')\n"
        "try:\n"
        f"    c = psycopg2.connect(host='{PG_HOST}', port={PG_PORT}, user='{PG_ADMIN_USER}', password='''{PG_ADMIN_PASSWORD}''', dbname='postgres', connect_timeout=5)\n"
        "    c.close()\n"
        "    print('OK')\n"
        "except Exception as e:\n"
        "    sys.exit('CONN_FAIL:' + str(e))\n"
    )
    rc, out, err = run_python_snippet(venv, snippet)
    if rc == 0:
        ok(f"PostgreSQL reachable at {PG_HOST}:{PG_PORT} (as {PG_ADMIN_USER})")
        return True
    fail(f"Cannot connect to Postgres as {PG_ADMIN_USER}", hint=err.splitlines()[0] if err else "")
    return False


def ensure_db_and_user(venv: Path) -> bool:
    """
    Using admin creds:
      1. Create app user if missing (with given password)
      2. Create target DB if missing (owned by app user)
      3. Grant all privileges on DB + public schema to app user
    """
    snippet = f"""
import sys, psycopg2
from psycopg2 import sql

ADMIN_HOST = {PG_HOST!r}
ADMIN_PORT = {PG_PORT!r}
ADMIN_USER = {PG_ADMIN_USER!r}
ADMIN_PWD  = {PG_ADMIN_PASSWORD!r}
APP_DB     = {PG_DATABASE!r}
APP_USER   = {PG_APP_USER!r}
APP_PWD    = {PG_APP_PASSWORD!r}

def connect(dbname):
    return psycopg2.connect(host=ADMIN_HOST, port=int(ADMIN_PORT),
                            user=ADMIN_USER, password=ADMIN_PWD,
                            dbname=dbname, connect_timeout=5)

try:
    c = connect('postgres'); c.autocommit = True; cur = c.cursor()

    # 1. user
    cur.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", (APP_USER,))
    if cur.fetchone() is None:
        cur.execute(sql.SQL("CREATE ROLE {{}} WITH LOGIN PASSWORD %s").format(sql.Identifier(APP_USER)), (APP_PWD,))
        print('USER_CREATED')
    else:
        cur.execute(sql.SQL("ALTER ROLE {{}} WITH LOGIN PASSWORD %s").format(sql.Identifier(APP_USER)), (APP_PWD,))
        print('USER_EXISTS')

    # 2. database
    cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (APP_DB,))
    if cur.fetchone() is None:
        cur.execute(sql.SQL("CREATE DATABASE {{}} OWNER {{}}").format(sql.Identifier(APP_DB), sql.Identifier(APP_USER)))
        print('DB_CREATED')
    else:
        print('DB_EXISTS')

    # 3. grants at DB level
    cur.execute(sql.SQL("GRANT ALL PRIVILEGES ON DATABASE {{}} TO {{}}").format(sql.Identifier(APP_DB), sql.Identifier(APP_USER)))
    cur.close(); c.close()

    # 4. grants inside the DB (public schema access for create + default schema perms)
    c = connect(APP_DB); c.autocommit = True; cur = c.cursor()
    cur.execute(sql.SQL("GRANT ALL ON SCHEMA public TO {{}}").format(sql.Identifier(APP_USER)))
    cur.close(); c.close()

    print('DONE')
except Exception as e:
    sys.exit('FAIL:' + str(e))
"""
    rc, out, err = run_python_snippet(venv, snippet)
    if rc != 0:
        fail("Could not set up DB + app user as admin", err.splitlines()[0] if err else "")
        return False
    lines = out.splitlines()
    if "USER_CREATED" in lines:
        ok(f"App user '{PG_APP_USER}' created")
    elif "USER_EXISTS" in lines:
        ok(f"App user '{PG_APP_USER}' already exists (password reset)")
    if "DB_CREATED" in lines:
        ok(f"Database '{PG_DATABASE}' created (owner: {PG_APP_USER})")
    elif "DB_EXISTS" in lines:
        ok(f"Database '{PG_DATABASE}' already exists")
    ok(f"Privileges granted on '{PG_DATABASE}' to '{PG_APP_USER}'")
    return True


def validate_postgres_app(venv: Path, db_url: str) -> bool:
    """Confirm the app user can now connect to the target DB."""
    host, port, user, password, dbname = parse_db_url(db_url)
    snippet = (
        "import sys, psycopg2\n"
        "try:\n"
        f"    c = psycopg2.connect(host='{host}', port={port}, user='{user}', password='''{password}''', dbname='{dbname}', connect_timeout=5)\n"
        "    c.close()\n"
        "    print('OK')\n"
        "except Exception as e:\n"
        "    sys.exit('FAIL:' + str(e))\n"
    )
    rc, out, err = run_python_snippet(venv, snippet)
    if rc == 0:
        ok(f"App user '{user}' can connect to '{dbname}'")
        return True
    fail(f"App user can't connect to '{dbname}'", err.splitlines()[0] if err else "")
    return False


def validate_mysql(venv: Path, mysql_url: str) -> bool:
    snippet = (
        "import sys\n"
        "try:\n"
        "    import pymysql\n"
        "except ImportError:\n"
        "    sys.exit('NO_DRIVER')\n"
        "from urllib.parse import urlparse, unquote\n"
        f"u = urlparse('{mysql_url}')\n"
        "try:\n"
        "    c = pymysql.connect(host=u.hostname, port=u.port or 3306, user=unquote(u.username or ''), password=unquote(u.password or ''), database=(u.path or '/').lstrip('/'), connect_timeout=5)\n"
        "    c.close()\n"
        "    print('OK')\n"
        "except Exception as e:\n"
        "    sys.exit('FAIL:' + str(e)[:200])\n"
    )
    rc, out, err = run_python_snippet(venv, snippet)
    if rc == 0:
        ok("MySQL source reachable")
        return True
    warn(f"MySQL source unreachable -- sensor DB syncing will fail")
    if err:
        warn(f"  details: {err.splitlines()[0]}")
    return False


def validate_sftp(venv: Path, host: str, port: str, user: str, password: str) -> bool:
    if not (host and user and password):
        SUMMARY.add_skipped("sFTP check", "credentials not provided")
        return True  # sFTP is optional
    snippet = (
        "import sys\n"
        "try:\n"
        "    import paramiko\n"
        "except ImportError:\n"
        "    sys.exit('NO_DRIVER')\n"
        "try:\n"
        f"    t = paramiko.Transport(('{host}', {port or 22}))\n"
        "    t.banner_timeout = 10\n"
        f"    t.connect(username='{user}', password='{password}')\n"
        "    t.close()\n"
        "    print('OK')\n"
        "except Exception as e:\n"
        "    sys.exit('FAIL:' + str(e)[:200])\n"
    )
    rc, out, err = run_python_snippet(venv, snippet)
    if rc == 0:
        ok(f"sFTP reachable at {host}:{port or 22}")
        return True
    warn(f"sFTP unreachable at {host}:{port or 22}")
    if err:
        warn(f"  details: {err.splitlines()[0]}")
    return False


def mount_smb_share():
    """Mount the SMB share as a drive on Windows, or skip on other OSes."""
    if not (SMB_SHARE and SMB_USER and SMB_PASSWORD and SMB_DRIVE):
        SUMMARY.add_skipped("SMB mount", "credentials not provided")
        return True

    if os.name != "nt":
        warn(f"Non-Windows: skipping auto-mount. Mount {SMB_SHARE} at {SMB_DRIVE} manually (mount.cifs) before running the pipeline.")
        return True

    # Check if already mounted
    drive_letter = SMB_DRIVE.rstrip("\\").rstrip(":")
    existing = Path(drive_letter + ":\\")
    if existing.exists():
        ok(f"{SMB_DRIVE} already appears mounted")
        return True

    # net use Z: \\server\share /USER:user password /PERSISTENT:YES
    try:
        subprocess.run(
            ["net", "use", SMB_DRIVE, SMB_SHARE,
             f"/USER:{SMB_USER}", SMB_PASSWORD,
             "/PERSISTENT:YES"],
            check=True,
            capture_output=True,
            text=True,
        )
        ok(f"Mounted {SMB_SHARE} -> {SMB_DRIVE}")
        return True
    except subprocess.CalledProcessError as e:
        stderr = (e.stderr or "").strip().splitlines()
        hint = stderr[0] if stderr else ""
        warn(f"Could not mount SMB share: {hint}")
        warn(f"  You can retry manually: net use {SMB_DRIVE} {SMB_SHARE} /USER:{SMB_USER} <password>")
        return False


def clone_repo(install_dir: Path):
    # Fresh clone
    if not install_dir.exists() or not any(install_dir.iterdir()):
        install_dir.parent.mkdir(parents=True, exist_ok=True)
        subprocess.run(
            ["git", "clone", "--branch", REPO_BRANCH, "--depth", "1", REPO_URL, str(install_dir)],
            check=True
        )
        ok(f"Repo cloned to {install_dir}")
        return

    # Existing dir — try to update it if it's the right repo
    if not (install_dir / ".git").exists():
        warn(f"{install_dir} already exists but isn't a git repo -- skipping update")
        return

    try:
        # Verify it's our repo
        res = subprocess.run(["git", "-C", str(install_dir), "remote", "get-url", "origin"],
                             capture_output=True, text=True, check=True)
        remote = res.stdout.strip()
        # Be tolerant of ssh vs https form
        if "data-cycle-domotic" not in remote:
            warn(f"{install_dir} is a git repo but points to {remote} -- skipping update")
            return

        # Fetch the branch (creates/updates FETCH_HEAD even on shallow clones
        # that were originally cloned with --branch=different)
        subprocess.run(["git", "-C", str(install_dir), "fetch", "--depth", "1", "origin", REPO_BRANCH],
                       check=True, capture_output=True)
        # Create or reset the local branch to point at what we just fetched,
        # then switch to it. Works even if the local repo never had this branch.
        subprocess.run(["git", "-C", str(install_dir), "checkout", "-B", REPO_BRANCH, "FETCH_HEAD"],
                       check=True, capture_output=True)
        ok(f"Repo updated to latest origin/{REPO_BRANCH}")
    except subprocess.CalledProcessError as e:
        warn(f"Could not update existing repo: {(e.stderr or b'').decode(errors='ignore').strip() or e}")
        warn("Delete the folder and rerun for a clean install.")


def write_env(install_dir: Path):
    env_path = install_dir / ".env"
    env_path.write_text(ENV_CONFIG, encoding="utf-8")
    ok(f".env written ({len(ENV_CONFIG)} chars)")


def create_venv(install_dir: Path) -> Path:
    venv = install_dir / ".venv"
    if venv.exists():
        warn(".venv already exists -- reusing")
    else:
        subprocess.run([sys.executable, "-m", "venv", str(venv)], check=True)
        ok("Virtual environment created")
    return venv


def venv_python(venv: Path) -> Path:
    if os.name == "nt":
        return venv / "Scripts" / "python.exe"
    return venv / "bin" / "python"


def install_deps(venv: Path, install_dir: Path):
    py = venv_python(venv)
    req = install_dir / "requirements.txt"
    if not req.exists():
        die(f"requirements.txt not found at {req}")
    subprocess.run([str(py), "-m", "pip", "install", "--upgrade", "pip", "--quiet"], check=True)
    subprocess.run([str(py), "-m", "pip", "install", "-r", str(req), "--quiet"], check=True)
    ok("Python dependencies installed")


def run_script(venv: Path, install_dir: Path, *args, label=None, env_extra=None):
    py = venv_python(venv)
    env = os.environ.copy()
    env["PYTHONPATH"] = str(install_dir)
    if env_extra:
        env.update(env_extra)
    try:
        subprocess.run([str(py), *args], cwd=str(install_dir), env=env, check=True)
        if label:
            ok(label)
    except subprocess.CalledProcessError as e:
        fail(f"{label or args} failed (exit {e.returncode})")
        raise


def admin_url() -> str:
    """Build postgresql://admin:pwd@host:port/postgres for the ETL scripts' DB_ADMIN_URL."""
    from urllib.parse import quote
    return (f"postgresql://{quote(PG_ADMIN_USER)}:{quote(PG_ADMIN_PASSWORD)}"
            f"@{PG_HOST}:{PG_PORT}/postgres")


def create_schemas(venv: Path, install_dir: Path):
    # Pass admin URL so create_silver/create_gold can CREATE SCHEMA
    env_extra = {"DB_ADMIN_URL": admin_url()}
    run_script(venv, install_dir, "-m", "etl.bronze_to_silver.create_silver",
               label="Silver schema created", env_extra=env_extra)
    run_script(venv, install_dir, "-m", "etl.silver_to_gold.create_gold",
               label="Gold schema created", env_extra=env_extra)


def import_mysql_dims(venv: Path, install_dir: Path):
    try:
        run_script(venv, install_dir, "-m", "etl.bronze_to_silver.import_mysql_to_silver",
                   label="MySQL dimensions imported to silver")
    except Exception as e:
        warn(f"MySQL dim import failed: {e}")
        warn("Continuing without MySQL dims — gold dim_apartment/room/device will be empty.")


def backfill_bronze_silver(venv: Path, install_dir: Path):
    """Run the full SMB + weather backfill. SMB part is optional (can be slow,
    20-60 min on first install), but weather is required for gold predictions
    to work, so we always run that.

    Re-runs are idempotent — bronze->silver skips already-processed files,
    weather skips already-downloaded forecasts."""
    # SMB part is opt-out (default Yes) — can be slow but everything depends
    # on it. Skipping it leaves gold facts empty.
    run_smb = True
    if sys.stdin.isatty():
        run_smb = ask_yes_no(
            "Run full SMB -> bronze -> silver backfill now? "
            "(20-60 min, idempotent — safe to re-run)", default=True)
    else:
        warn("Non-interactive: defaulting to YES for SMB backfill")

    if run_smb:
        print(f"{DIM}  Scanning SMB + running bronze->silver pipeline...{RESET}")
        try:
            run_script(venv, install_dir, "ingestion/fast_flow/watcher.py", "--scan",
                       label="SMB backfill complete")
        except Exception as e:
            warn(f"SMB backfill failed: {e}")
            warn("  You can re-run later: python ingestion/fast_flow/watcher.py --scan")
    else:
        warn("Skipped SMB backfill. Re-run later with: "
             "python ingestion/fast_flow/watcher.py --scan")

    # Weather is REQUIRED — gold.fact_weather_hour and the consumption
    # prediction workflow both depend on it. Always run, no prompt.
    print(f"{DIM}  Downloading weather + cleaning to silver "
          f"(required for gold predictions)...{RESET}")
    try:
        run_script(venv, install_dir, "ingestion/fast_flow/watcher.py", "--weather",
                   label="Weather backfill complete")
    except Exception as e:
        warn(f"Weather backfill failed: {e}")
        warn("  Predictions will fail until this succeeds. Re-run later: "
             "python ingestion/fast_flow/watcher.py --weather")


def run_initial_etl(venv: Path, install_dir: Path):
    run_script(venv, install_dir, "-m", "etl.silver_to_gold.populate_gold", label="Initial gold ETL complete")


def configure_bi_knime(venv: Path, install_dir: Path):
    """Auto-patch .pbix and .knwf files to use the user's local DB,
    then deploy the .knwf workflows to the KNIME workspace if KNIME is installed."""
    script = install_dir / "scripts" / "configure_bi_knime.py"
    if not script.exists():
        warn("configure_bi_knime.py not in repo, skipping auto-patch")
    else:
        try:
            run_script(venv, install_dir, str(script), label="BI + KNIME configured")
        except Exception as e:
            warn(f"Auto-patch had issues: {e}")
            warn("You'll need to repoint Power BI / KNIME manually -- see Next steps below.")
    # Auto-deploy the KNIME workflows into the KNIME workspace (if KNIME exists)
    deploy_knime_workflows(install_dir)


def maybe_open_powerbi(install_dir: Path):
    if not sys.stdin.isatty():
        return
    pbix = install_dir / "bi" / "power_bi" / "DataCycleDomotic.pbix"
    if not pbix.exists():
        return
    pbi_exe = find_power_bi()
    if not pbi_exe:
        warn("Power BI Desktop not installed -- skipping the 'open dashboard' step.")
        warn(f"  Install from https://www.microsoft.com/en-us/download/details.aspx?id=58494")
        warn(f"  then double-click: {pbix}")
        return
    if not ask_yes_no("Open the Power BI dashboard now?", default=True):
        return
    try:
        # Launch via the detected exe rather than os.startfile, so we don't
        # trigger the 'choose an app' dialog if .pbix isn't associated.
        subprocess.Popen([str(pbi_exe), str(pbix)])
        ok(f"Launched Power BI Desktop -> {pbix.name}")
    except Exception as e:
        warn(f"Could not auto-open: {e}")


def find_power_bi():
    """Locate Power BI Desktop on Windows. Returns Path or None."""
    if os.name != "nt":
        return None  # Power BI Desktop is Windows-only
    candidates = [
        Path(r"C:\Program Files\Microsoft Power BI Desktop\bin\PBIDesktop.exe"),
        Path(r"C:\Program Files (x86)\Microsoft Power BI Desktop\bin\PBIDesktop.exe"),
    ]
    for c in candidates:
        if c.exists():
            return c
    # Microsoft Store version
    import glob
    store_pattern = os.path.expanduser(r"~\AppData\Local\Microsoft\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_*\PBIDesktopStore.exe")
    matches = glob.glob(store_pattern)
    if matches:
        return Path(matches[0])
    return None


def find_knime():
    """Locate KNIME Analytics Platform on this machine. Returns Path or None."""
    candidates = []
    if os.name == "nt":
        candidates += [
            Path(r"C:\Program Files\KNIME\knime.exe"),
            Path(r"C:\Program Files (x86)\KNIME\knime.exe"),
            Path(os.path.expanduser(r"~\AppData\Local\KNIME\knime.exe")),
        ]
    elif sys.platform == "darwin":
        candidates += [Path("/Applications/KNIME.app/Contents/MacOS/Knime")]
    else:
        candidates += [
            Path("/opt/knime/knime"),
            Path(os.path.expanduser("~/knime/knime")),
            Path("/usr/local/bin/knime"),
        ]
    for c in candidates:
        if c.exists():
            return c
    on_path = shutil.which("knime")
    return Path(on_path) if on_path else None


def deploy_knime_workflows(install_dir: Path):
    """If KNIME is installed, extract .knwf files into its workspace
    so they appear in the Knime Explorer next time KNIME starts."""
    import zipfile
    workflows_dir = install_dir / "ml" / "knime"
    if not workflows_dir.exists():
        return False
    knwfs = list(workflows_dir.glob("*.knwf"))
    if not knwfs:
        return False

    knime_exe = find_knime()
    if not knime_exe:
        warn("KNIME Analytics Platform not detected on this machine.")
        warn("  The pipeline still works without it -- only the ML predictions step is skipped.")
        warn("  To enable: install from https://www.knime.com/downloads then rerun this installer")
        warn("  (it will auto-detect KNIME and drop the workflows into your workspace).")
        return False

    ok(f"KNIME detected: {knime_exe}")

    # Default KNIME workspace
    workspace = Path(os.path.expanduser("~/knime-workspace"))
    workspace.mkdir(parents=True, exist_ok=True)

    deployed = skipped = 0
    for knwf in knwfs:
        target = workspace / knwf.stem
        if target.exists():
            warn(f"  {knwf.stem} already in {workspace.name}, skipping")
            skipped += 1
            continue
        try:
            with zipfile.ZipFile(knwf) as zf:
                zf.extractall(workspace)
            ok(f"  Deployed {knwf.stem} to KNIME workspace")
            deployed += 1
        except Exception as e:
            warn(f"  Could not deploy {knwf.name}: {e}")

    if deployed > 0:
        ok(f"{deployed} workflow(s) deployed. Open KNIME -- they will appear in the KNIME Explorer.")
    return True


def maybe_run_predictions(venv: Path, install_dir: Path):
    """At the end of install, offer to run the KNIME prediction workflows
    headlessly so predictions land in gold.fact_prediction without the
    user opening KNIME at all."""
    if not sys.stdin.isatty():
        return
    knime_exe = find_knime()
    if not knime_exe:
        # Fallback: just open the folder so the user can see the .knwf files
        folder = install_dir / "ml" / "knime"
        if not folder.exists():
            return
        if not ask_yes_no("Open the KNIME workflows folder?", default=False):
            return
        try:
            if os.name == "nt":
                os.startfile(str(folder))  # type: ignore[attr-defined]
            elif sys.platform == "darwin":
                subprocess.Popen(["open", str(folder)])
            else:
                subprocess.Popen(["xdg-open", str(folder)])
            ok(f"Opened {folder}")
        except Exception as e:
            warn(f"Could not open folder: {e}")
        return

    runner = install_dir / "scripts" / "run_knime_predictions.py"
    if not runner.exists():
        warn("scripts/run_knime_predictions.py not found, skipping")
        return

    print()
    print(f"  {DIM}KNIME workflows can be run now in batch mode (no GUI).{RESET}")
    print(f"  {DIM}This writes predictions into gold.fact_prediction.{RESET}")
    print(f"  {DIM}Takes 5-30 minutes depending on data volume.{RESET}")
    if not ask_yes_no("Run KNIME prediction workflows now?", default=False):
        warn(f"Skipped. Run later: {DIM}python scripts/run_knime_predictions.py{RESET}")
        return

    try:
        run_script(venv, install_dir, str(runner), label="KNIME predictions complete")
    except Exception as e:
        warn(f"Predictions runner failed: {e}")
        warn(f"Try manually: python scripts/run_knime_predictions.py")
        warn(f"  (or open the workflow once in KNIME and check the PostgreSQL Connector setup)")


def verify_data(venv: Path, db_url: str):
    """Quick sanity check: count rows in key gold tables."""
    host, port, user, password, dbname = parse_db_url(db_url)
    snippet = (
        "import psycopg2, sys\n"
        f"c = psycopg2.connect(host='{host}', port={port}, user='{user}', password='{password}', dbname='{dbname}', connect_timeout=5)\n"
        "cur = c.cursor()\n"
        "for t in ['dim_apartment','dim_room','dim_device','fact_environment_minute','fact_energy_minute','fact_presence_minute']:\n"
        "    try:\n"
        "        cur.execute(f'SELECT COUNT(*) FROM gold.{t}')\n"
        "        print(f'{t}\\t{cur.fetchone()[0]}')\n"
        "    except Exception as e:\n"
        "        print(f'{t}\\tERR: ' + str(e)[:60])\n"
        "cur.close(); c.close()\n"
    )
    rc, out, err = run_python_snippet(venv, snippet)
    if rc != 0:
        warn(f"Verification query failed: {err or out}")
        return
    for line in out.splitlines():
        parts = line.split("\t")
        if len(parts) == 2:
            t, n = parts
            if n.startswith("ERR"):
                fail(f"  gold.{t} — {n}")
            elif int(n) == 0:
                warn(f"  gold.{t} — empty")
            else:
                ok(f"  gold.{t} — {int(n):,} rows")


def maybe_start_watcher(venv: Path, install_dir: Path):
    if not sys.stdin.isatty():
        return
    if not ask_yes_no("Start the watcher now? (runs continuously in this terminal)", default=False):
        return
    print()
    print(f"{DIM}Starting watcher... Ctrl+C to stop.{RESET}")
    py = venv_python(venv)
    env = os.environ.copy()
    env["PYTHONPATH"] = str(install_dir)
    try:
        subprocess.run([str(py), "ingestion/fast_flow/watcher.py"], cwd=str(install_dir), env=env)
    except KeyboardInterrupt:
        print(f"\n{DIM}Watcher stopped.{RESET}")


# =============================================================================
# MAIN
# =============================================================================

def main():
    banner()

    # ── Parse args (positional: install path; flags: --skip-* / --help) ──
    flags = {a for a in sys.argv[1:] if a.startswith("-")}
    positional = [a for a in sys.argv[1:] if not a.startswith("-")]

    if "-h" in flags or "--help" in flags:
        print("""
Usage: python data-cycle-installer.py [path] [flags]

  path            Where to install (default: ./data-cycle-domotic)

Flags:
  --skip-etl      Skip the initial gold ETL (step 8). Useful when you just
                  want to update the repo / redeploy KNIME workflows / refresh
                  configs without waiting for the full silver -> gold rebuild.
  --skip-mysql    Skip the MySQL dim sync inside step 7.
  --skip-deps     Skip 'pip install -r requirements.txt' (assumes venv is OK).
  -h, --help      Show this message.
""")
        sys.exit(0)

    SKIP_ETL   = "--skip-etl"   in flags
    SKIP_MYSQL = "--skip-mysql" in flags
    SKIP_DEPS  = "--skip-deps"  in flags

    install_path = Path(positional[0]).expanduser().resolve() if positional \
                   else Path.cwd() / DEFAULT_INSTALL_DIR

    print(f"Install target: {BOLD}{install_path}{RESET}")
    if SKIP_ETL or SKIP_MYSQL or SKIP_DEPS:
        skipped = ", ".join(f for f in ["etl" if SKIP_ETL else None,
                                        "mysql" if SKIP_MYSQL else None,
                                        "deps" if SKIP_DEPS else None] if f)
        print(f"Skipping: {YELLOW}{skipped}{RESET}")

    # ── 1. Prerequisites ────────────────────────────────────────────────────
    step(1, 9, "Checking prerequisites")
    check_python()
    check_cmd("git", "Install Git from https://git-scm.com/downloads")
    # Optional tools — warn but don't die
    pbi = find_power_bi()
    if pbi:
        ok(f"Power BI Desktop: {pbi.name}")
    else:
        if os.name == "nt":
            warn("Power BI Desktop not detected. Pipeline will run, but you won't be able to open the dashboard.")
            warn("  Install from https://www.microsoft.com/en-us/download/details.aspx?id=58494")
        else:
            warn("Power BI Desktop is Windows-only. Skipping dashboard step (pipeline still runs).")
    knime = find_knime()
    if knime:
        ok(f"KNIME: {knime}")
    else:
        warn("KNIME Analytics Platform not detected. Pipeline will run, but ML predictions step will be skipped.")
        warn("  Install from https://www.knime.com/downloads")

    # ── 2. Clone repo ──────────────────────────────────────────────────────
    step(2, 9, "Cloning repository")
    clone_repo(install_path)

    # ── 3. Write .env ──────────────────────────────────────────────────────
    step(3, 9, "Writing .env configuration")
    write_env(install_path)

    # ── 4. Create venv + deps ──────────────────────────────────────────────
    step(4, 9, "Setting up Python environment")
    venv = create_venv(install_path)
    if SKIP_DEPS:
        warn("--skip-deps set, leaving venv as-is")
    else:
        install_deps(venv, install_path)

    # ── 5. Pre-flight connectivity checks ─────────────────────────────────
    step(5, 9, "Pre-flight connectivity checks")
    mount_smb_share()  # best-effort, warns on failure


    import re
    db_m      = re.search(r"DB_URL=(.+)",       ENV_CONFIG)
    mysql_m   = re.search(r"MYSQL_URL=(.+)",    ENV_CONFIG)
    sftp_h    = re.search(r"SFTP_HOST=(.*)",    ENV_CONFIG)
    sftp_p    = re.search(r"SFTP_PORT=(.*)",    ENV_CONFIG)
    sftp_u    = re.search(r"SFTP_USER=(.*)",    ENV_CONFIG)
    sftp_pw   = re.search(r"SFTP_PASSWORD=(.*)",ENV_CONFIG)

    db_url = db_m.group(1).strip() if db_m else ""
    if not validate_postgres_admin(venv):
        die("Fix your admin credentials (or start PostgreSQL) and rerun.")

    if mysql_m:
        validate_mysql(venv, mysql_m.group(1).strip())  # warn only, don't die
    if sftp_h:
        validate_sftp(venv,
                      sftp_h.group(1).strip(),
                      sftp_p.group(1).strip() if sftp_p else "22",
                      sftp_u.group(1).strip() if sftp_u else "",
                      sftp_pw.group(1).strip() if sftp_pw else "")

    # ── 6. Create app user + DB, then schemas ──────────────────────────────
    step(6, 9, "Creating PostgreSQL user, database + schemas")
    if not ensure_db_and_user(venv):
        die("DB + user setup failed. Check admin credentials.")
    if db_url and not validate_postgres_app(venv, db_url):
        die("App user connection failed. Check username/password.")
    try:
        create_schemas(venv, install_path)
    except Exception as e:
        warn(f"Schema creation had issues: {e}")

    # ── 7. Bootstrap silver (MySQL dims + optional full backfill) ──────────
    step(7, 9, "Bootstrapping silver layer")
    if SKIP_MYSQL:
        warn("--skip-mysql set, skipping MySQL dim import")
    else:
        import_mysql_dims(venv, install_path)
    backfill_bronze_silver(venv, install_path)

    # ── 8. Initial gold ETL ────────────────────────────────────────────────
    step(8, 9, "Running initial gold ETL")
    if SKIP_ETL:
        warn("--skip-etl set, skipping populate_gold (run manually with: python -m etl.silver_to_gold.populate_gold)")
    else:
        try:
            run_initial_etl(venv, install_path)
        except Exception as e:
            warn(f"Initial ETL had issues: {e}")
            warn("You can re-run manually: python -m etl.silver_to_gold.populate_gold")

    # ── 9. Verify + auto-config BI/KNIME ──────────────────────────────────
    step(9, 9, "Verifying + configuring BI/KNIME")
    if db_url:
        verify_data(venv, db_url)
    configure_bi_knime(venv, install_path)

    # ── Done ───────────────────────────────────────────────────────────────
    print()
    print(f"{GREEN}{BOLD}╔══════════════════════════════════════════════════════════════╗{RESET}")
    print(f"{GREEN}{BOLD}║                     Installation complete!                   ║{RESET}")
    print(f"{GREEN}{BOLD}╚══════════════════════════════════════════════════════════════╝{RESET}")
    print()

    print(f"{BOLD}Next steps:{RESET}\n")

    print(f"  {DIM}1.{RESET} {BOLD}Open the Power BI dashboard:{RESET}")
    print(f"     {install_path / 'bi' / 'power_bi' / 'DataCycleDomotic.pbix'}")
    print(f"     {DIM}First open: Power BI will fail to refresh because the .pbix points{RESET}")
    print(f"     {DIM}at a different database. To fix:{RESET}")
    print(f"     {DIM}  - Click 'Transform data' -> 'Data source settings'{RESET}")
    print(f"     {DIM}  - Select the PostgreSQL source -> 'Change Source...'{RESET}")
    print(f"     {DIM}  - Server   = {PG_HOST}:{PG_PORT}{RESET}")
    print(f"     {DIM}  - Database = {PG_DATABASE}{RESET}")
    print(f"     {DIM}  - 'Edit Permissions' -> Database creds:{RESET}")
    print(f"     {DIM}      User     = {PG_APP_USER}{RESET}")
    print(f"     {DIM}      Password = (your app password){RESET}")
    print(f"     {DIM}  - Close & Apply, then Home -> Refresh{RESET}")
    print()

    print(f"  {DIM}2.{RESET} {BOLD}Start the continuous pipeline (watcher):{RESET}")
    print(f"     cd {install_path}")
    if os.name == "nt":
        print(f"     .venv\\Scripts\\python.exe ingestion\\fast_flow\\watcher.py")
    else:
        print(f"     .venv/bin/python ingestion/fast_flow/watcher.py")
    print()

    print(f"  {DIM}3.{RESET} {BOLD}Run ML predictions in KNIME (headless, no GUI):{RESET}")
    if os.name == "nt":
        print(f"     .venv\\Scripts\\python.exe scripts\\run_knime_predictions.py")
    else:
        print(f"     .venv/bin/python scripts/run_knime_predictions.py")
    print(f"     {DIM}(Reads .env, injects DB credentials at runtime — no manual setup{RESET}")
    print(f"     {DIM} needed. Predictions land in gold.fact_prediction_*.){RESET}")
    print()

    write_log()
    print(f"{DIM}Install log saved to install.log{RESET}")
    print()

    # Interactive: auto-open Power BI + KNIME + start watcher
    maybe_open_powerbi(install_path)
    maybe_run_predictions(venv, install_path)
    maybe_start_watcher(venv, install_path)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print(f"\n{YELLOW}Interrupted by user.{RESET}")
        write_log()
        sys.exit(130)
    except subprocess.CalledProcessError as e:
        print(f"\n{RED}{BOLD}A subprocess failed (exit {e.returncode}).{RESET}")
        print(f"{DIM}Command: {' '.join(str(x) for x in e.cmd)}{RESET}")
        write_log()
        sys.exit(1)
    except Exception as e:
        print(f"\n{RED}{BOLD}Unexpected error:{RESET} {e}")
        write_log()
        sys.exit(1)
